# Generated by Django 3.0.4 on 2020-03-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infostore',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='infostore',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
