# Generated by Django 3.0.4 on 2020-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200310_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostore',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
