# Generated by Django 3.0.4 on 2020-03-10 10:08

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200310_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostore',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=11),
        ),
    ]
